# Generated by Django 4.2.2 on 2023-06-30 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('person_phone_number', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('requirement_description', models.TextField()),
                ('intro', models.TextField(blank=True, null=True)),
                ('free_text', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_quantity', models.IntegerField()),
                ('price_estimate', models.IntegerField(default=5)),
                ('production_estimate', models.IntegerField(default=5)),
                ('attribute_prefix', models.CharField(max_length=255)),
                ('attribute_suffix', models.CharField(max_length=255)),
                ('product_list_title', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_pedido.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='bot_pedido.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_delivery', models.CharField(choices=[('PU', 'Pickup'), ('DE', 'Delivery')], default='PU', max_length=2)),
                ('product_detail', models.TextField()),
                ('specs', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('extra_details', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_pedido.client')),
            ],
        ),
    ]
